### ISSUE TITLE
Custom styles are not maintained after temporary events

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#23]
When a node or link is styled, eg. from a morph or group styling, and then a temporary event (eg. a mouse hover) changes that style, it resets back to a default value. This should be changed so that group/morph style changes are static and are reverted back to after a temporary event modifies the style.

**Comment by sergeichestakov** [comment]
In which demo(s) was this a problem? I'll take a look but I'm not sure that this is the best solution now as constantly modifying and iterating through a dictionary is both difficult to implement as we add more features and can be computationally expensive. 

Imagine a user hovering over a large amount of nodes/links in a short period, and clicking/dragging a few. If we had to look up and modify every element in the dictionary every time each event started and ended, there will most likely be performance issues and delays, especially on very large datasets. Additionally, the space required for this is very large for the marginal benefits it provides. I think we should aim to decrease space of the Network object as it is already quite large at this point and we don't want to have to store several objects that are the linear to the size of the dataset since that can grow very quickly. 

If this really is a problem that we need to address, it might be easier to store only the previous style of the node/link and revert after an event is finished. This would be better as it would cover most cases and could be stored in the adjacency list to avoid creating a whole new dictionary. Let me know what you think.

**Comment by mattrasto** [comment]
This was observed in the `morphs.html` demo when a user applied the morphs and then hovered in and then out of one of the modified nodes. After our discussion last night, we should stick with this plan. However, first we need to implement proper event handler wrapper functions (#45) so that we're able to modify the style map on the occurrence of any arbitrary event that affects the style of an element.

**Comment by mattrasto** [comment]
After a working version of stylemaps, we've decided that they provide too much code complexity for too little benefit, will cause maintainability nightmares, and that styling should be user-controlled instead of having unintuitive/unexpected default behavior. Styles will revert to old function.

**Comment by sergeichestakov** [comment]
HA I told you!

**Comment by mattrasto** [comment]
@Github I need angry reax
