### ISSUE TITLE
Changing viz settings in "update settings" demo breaks element styling

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#48]
When a viz setting (zoom, gravity, charge, link strength, or link distance) is changed in the "update settings" demo, the remaining styling options cease to update the visualization on change. These styling updates are successfully applied before the viz settings is applied.

My intuition is that this has to do with the rerendering of the network. The styling options are applied by calling `.style()` on the "all" node/link groups, which are default to the visualization. We can start by investigating how these groups are affected by a call to `viz.reset()`

**Comment by sergeichestakov** [comment]
I fixed the problem you're referring to by recalling the nodeGroup and linkGroup functions on all the existing groups so that they are bound to the new svg that is created. This works, but removes all of the user applied styles and renders all the bars in the demo to be inaccurate until moved again. 

It would be nice to save those styles and reapply them after rerendering, but I'm not sure what the best way to do that is. Is there a way to save all the styles applied to a given node group and be able to reapply them after resetting the graph?
