### ISSUE TITLE
Consolidate phase state

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#51]
Some of the "private" instance variables in the Phase class, such as `_timeStep`, `_curLayer`, etc. could be moved into an internal part of the `_state` variable. Additionally, the phase state could include useful debugging data such as the current progression of the phase, how many times it's been run, and (if a `debug` setting is enabled) log interactions with the phase.

**Comment by sergeichestakov** [comment]
Not sure about this one. `this.curLayer` and `this.layerNodes` are not actually used anywhere, and I think that timestep is fine as it's own variable given it's use. There is also a `this.phaseState` variable already so that might get confusing. I believe we moved away from the layers API so I think it's safe to remove them.

**Comment by sergeichestakov** [comment]
I removed the variables we no longer use within phase.js and it seems there isn't much to consolidate. Closing the issue for now until there is a need to reopen should we decide to modify the API.
