### ISSUE TITLE
Refactor to follow Airbnb Style Guide

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#60]
The Phase source code should follow styling and conventions outlined in the Airbnb Style Guide (https://github.com/airbnb/javascript). We should include a `.eslintrc` file and include ESLint in the `package.json` dependencies.

**Comment by sergeichestakov** [comment]
This might be useful: https://www.npmjs.com/package/eslint-config-airbnb-base

**Comment by sergeichestakov** [comment]
It's important to note that the Airbnb style guide discourages the use of a trailing underscore to signify "private" variables (see https://github.com/airbnb/javascript#naming--leading-underscore). I agree with this and think we should move towards removing that naming convention since it's not actually private and we do it rather inconsistently. 

I've looked into other alternatives and this one seems promising: https://github.com/philipwalton/private-parts. This involves considerable refactoring, however, and we should consider how badly we need these variables/methods to be private. If we do want to keep mostly everything private, then I think we should decide on a viable alternative like that one that maintains true privacy.

**Comment by mattrasto** [comment]
We have no need to purposely obfuscate any class variables - it was mostly a semantic distinction. I like the idea of Private Parts, but I think it'll be much less headache if we just make everything public.

**Comment by sergeichestakov** [comment]
Yeah I agree. I don't think it's a big deal since we can just leave all the "private" stuff undocumented and it would lead to unhelpful behavior for the user if they try to use it so I doubt anyone would feel the need to. Let's just remove the leading underscores when we refactor according to the linting rules.

**Comment by Ac2zoom** [comment]
> This might be useful: https://www.npmjs.com/package/eslint-config-airbnb-base

Turns out eslint --int automatically references this; can remove the requirement for this down the line
