### ISSUE TITLE
Add dataset generation script

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#61]
To effectively test the framework, we need to create demos that operate on networks of different structures. At the moment, most demos use the Les Miserables dataset. It would improve our testing flow if we had a script that generated datasets given a few network structure heuristics. The following heuristics should be supported in the base version:

1. Number of nodes
2. Number of edges (or degree of connectedness)
3. Specific types of subnetworks present (hubs, fully-connected subgraphs, etc.)
4. Connected vs. disconnected

**Comment by sergeichestakov** [comment]
While I agree this would be useful, I don't think we need to overdo it on datasets. It might be best to keep the number of datasets small, but make sure that each one is unique and represents a specific edge case. For example, one thing we're missing now is a dataset that demonstrates the use of phase at scale (e.g 100s or 1000s of nodes/links). 

If we did create a script, how would you generate the data (such as the IDs of the nodes and values of the links)? It would be trivial to randomize everything, but it might be more ideal to base values off reality and use actual data sources like [these](http://snap.stanford.edu/data/index.html) to demonstrate the utility of phase, rather than just meaningless numbers/strings. Let me know what you think.

**Comment by mattrasto** [comment]
You're correct in that using real-world datasets, such as those from SNAP, would be better. However, the datasets contained in most data repositories are far too large for the average use case of Phase - we would need to select only a subnetwork, which is not extensible and requires just about as much work as the generation script would. I still think a quick, basic script would be helpful for the time being, and we can continue to use real-world datasets when possible.

**Comment by sergeichestakov** [comment]
That's fair. I agree the script is a good idea for now since those datasets are def too large for our current use cases, but it would be interesting to have at least one decently sized real world dataset just to see how Phase handles it.

**Comment by mattrasto** [comment]
Commit 4e23a80 merged into dev.
