### ISSUE TITLE
Distribute v1.0.0 on public CDN

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#69]
The first public release of the framework should be accessible via a public CDN, such as [cdnjs](https://cdnjs.com/).

**Comment by sergeichestakov** [comment]
Our repo is already accessible via [jsDelivr](https://www.jsdelivr.com/?docs=gh).

The only problem is that we need to store the packaged and minified file that is normally outputted in the gitignored `dist` file (phase.min.js). I recommend creating an anonymous branch and publishing the file in a dist folder on each release as described [here](https://stackoverflow.com/questions/50974474/how-to-save-dist-build-files-on-github-release-but-not-in-master).

This solution seems ideal for our use case, but I'm open to other suggestions. In this case, it is best to stick to only using numbers in the tag names (e.g `1.0.0` instead of `v1.0.0`) to simplify the URL. 

Closing for now as this change is trivial to make once we're ready to release.
